"""
Situation report generator.

Produces a concise, professional text summary of analysis results.
"""

from datetime import datetime, timezone


def _severity_label(avg_score: float) -> str:
    if avg_score >= 0.75:
        return "CRITICAL"
    elif avg_score >= 0.5:
        return "SEVERE"
    elif avg_score >= 0.25:
        return "MODERATE"
    elif avg_score > 0.0:
        return "MINOR"
    return "NEGLIGIBLE"


def generate_report(stats: dict, top_tiles: list) -> str:
    """
    Generate a plain-text situation report from aggregate stats and top-priority tiles.
    """
    if not stats or stats.get("ok_tiles", 0) == 0:
        return "Insufficient data to generate a situation report."

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pct = stats.get("class_percentages", {})
    counts = stats.get("class_counts", {})
    avg_sev = stats.get("avg_severity_score", 0.0)
    avg_conf = stats.get("avg_confidence", 0.0)
    total = stats.get("total_tiles", 0)
    ok = stats.get("ok_tiles", 0)
    failed = stats.get("failed_tiles", 0)

    severity_label = _severity_label(avg_sev)

    # Top-priority tile summaries
    priority_lines = []
    for i, t in enumerate(top_tiles[:5], start=1):
        priority_lines.append(
            f"  {i}. Tile {t['tile_id']} - {t['damage_class'].upper()} "
            f"({t['confidence']:.0%} confidence, priority {t['priority_score']:.2f})"
        )
    priority_block = "\n".join(priority_lines) if priority_lines else "  No high-priority tiles identified."

    # Confidence note
    if avg_conf >= 0.80:
        conf_note = "Model confidence is HIGH. Results are reliable for operational use."
    elif avg_conf >= 0.60:
        conf_note = "Model confidence is MODERATE. Results should be cross-checked with field teams."
    else:
        conf_note = "Model confidence is LOW. Ground-truth verification is strongly recommended."

    report = f"""
// INTACT - DISASTERVISION
// SITUATION REPORT
// GENERATED: {now}


[ OVERALL ASSESSMENT ]
> {severity_label}

[ REGION SUMMARY ]
Tiles analyzed      :  {total}
Successfully scored :  {ok}
Failed (errors)     :  {failed}
Average severity    :  {avg_sev:.2f} / 1.00
Average confidence  :  {avg_conf:.0%}

[ DAMAGE BREAKDOWN ]
  - No Damage :  {counts.get('no-damage', 0):>3} tiles  ({pct.get('no-damage', 0):.1f}%)
  - Minor     :  {counts.get('minor', 0):>3} tiles  ({pct.get('minor', 0):.1f}%)
  - Major     :  {counts.get('major', 0):>3} tiles  ({pct.get('major', 0):.1f}%)
  - Destroyed :  {counts.get('destroyed', 0):>3} tiles  ({pct.get('destroyed', 0):.1f}%)

[ TOP PRIORITY ZONES ]
{priority_block}

[ RESPONSE GUIDANCE ]
"""

    # Dynamic response guidance
    if pct.get("destroyed", 0) > 20 or pct.get("major", 0) > 30:
        report += """  > Immediate life-safety response is recommended.
  > Deploy search-and-rescue assets to top-priority tiles first.
  > Coordinate with local emergency management for resource staging.
"""
    elif pct.get("major", 0) > 10 or pct.get("minor", 0) > 30:
        report += """  > Significant damage detected. Rapid damage assessment teams advised.
  > Prioritize infrastructure inspection in marked major-damage zones.
  > Monitor situation for escalation.
"""
    else:
        report += """  > Damage appears limited. Standard monitoring protocols apply.
  > Conduct targeted field inspections in flagged zones.
"""

    report += f"""
[ CONFIDENCE NOTES ]
{conf_note}

// DISCLAIMER
// This report is generated by an AI model and is intended as a
// decision-support tool only. Assessment should be validated by
// qualified personnel before operational deployment.
"""
    return report

